#!/bin/bash
#
# Generates C Program Project Skeletons Simply and Properly
# Justine Tunney <jtunney@lobstertech.com>
# Licensed MIT
#

PROJ=$1

[ -z "$PROJ" ]               && ( echo "missing name!" >&2; exit 1 )
[ -f "$PROJ" ]               && ( echo "$PROJ already exists!" >&2; exit 1 )
[ -z "$LIBS" ]               && LIBS=""
[ -z "$DEST" ]               && DEST="."
[ -z "$EMAIL" ]              && EMAIL="$(git config user.email)"
[ -z "$EMAIL" ]              && EMAIL="$USER@$(hostname -f)"
[ -z "$AUTHOR" ]             && AUTHOR="$(git config user.name)"
[ -z "$AUTHOR" ]             && AUTHOR="$USER"
[ -z "$DESCRIP" ]            && DESCRIP="$PROJ"
[ -z "$LICENSE" ]            && LICENSE="GNU AGPL v3 or later"

for s in $LIBS; do
    pkg-config $s || exit $?
done

if apt-get -v >/dev/null; then
    PKGS="build-essential libtool autoconf automake pkg-config"
    echo sudo apt-get install -y $PKGS
    sudo apt-get install -y $PKGS
fi

mkdir $PROJ
cd $PROJ

mkdir -p doc
mkdir -p src/test

echo "generating .gitignore..."
cat >.gitignore <<EOF
# stuff for this project
./$PROJ

# typical c project stuff
*.~
*.o
*.a
*.lo
*.la
*.pyc
doc
core
vgcore.*
callgrind.out
TAGS
.libs
.gdb_history

# libtoolize/aclocal should make these for us
m4/pkg.m4
m4/libtool.m4
m4/ltoptions.m4
m4/ltsugar.m4
m4/ltversion.m4
m4/lt~obsolete.m4

# trash autotools leaves laying around
.deps
config
libtool
stamp-h1
Makefile
config.h
configure
aclocal.m4
config.log
Makefile.in
config.h.in
config.h.in~
config.cache
config.status
autom4te.cache
EOF

echo "generating README.rst..."
cat >README.rst <<EOF
.. -*-rst-*-

=$(echo $PROJ | sed s/./=/g)=
 $PROJ
=$(echo $PROJ | sed s/./=/g)=

:name:        $PROJ
:description: $DESCRIP
:copyright:   © $(date +%Y) $AUTHOR
:license:     $LICENSE


Setup
=====

How to install::

    ./configure
    make
    sudo make install

How to run::

    $PROJ


Developers
----------

Stuff you should install::

    sudo apt-get install build-essential libtool autoconf automake pkg-config
    sudo apt-get install gdb valgrind strace ltrace tshark

How to build::

    ./autogen.sh
    ./configure -C CFLAGS="-g3 -O0 -Wall -pedantic"
    make

How to test::

    make check
    ./leak ./test
EOF

######################################################################

echo "generating Makefile.am..."
cat >Makefile.am <<EOF
NAME = $PROJ
AUTOMAKE_OPTS = foreign
ACLOCAL_AMFLAGS = -I m4
EXTRA_DIST = autogen.sh

bin_PROGRAMS = $PROJ

${PROJ}_SOURCES = src/$PROJ.c src/$PROJ.h
${PROJ}_CFLAGS  = -Isrc -I@includedir@$(for s in $LIBS; do echo -n " \$($(echo $s | tr a-z A-Z | tr - _)_CFLAGS)"; done)
${PROJ}_LDADD   =$(for s in $LIBS; do echo -n " \$($(echo $s | tr a-z A-Z | tr - _)_LIBS)"; done)

check_PROGRAMS = test
TESTS = \$(check_PROGRAMS)

test_SOURCES = src/test/test.c
test_CFLAGS  = -Isrc -I@includedir@$(for s in $LIBS; do echo -n " \$($(echo $s | tr a-z A-Z | tr - _)_CFLAGS)"; done)
test_LDADD   =$(for s in $LIBS; do echo -n " \$($(echo $s | tr a-z A-Z | tr - _)_LIBS)"; done)

maintainer-clean-local: clean-doc
	rm -rf config
	rm -f aclocal.m4 config.h* configure Makefile.in \\
	      m4/pkg.m4 m4/libtool.m4 m4/ltoptions.m4 m4/ltsugar.m4 \\
	      m4/ltversion.m4 m4/lt~obsolete.m4
	find . -type f -name \*.pyc   \\
	       -or -name \*~          \\
	       -or -name -name \.*~   \\
	       -or -name \#\*         \\
	       -or -name \.\#\*       \\
	       -or -name core\*       \\
	       -or -name vgcore\*     \\
	    | xargs rm -f
EOF

######################################################################

echo "generating configure.ac..."
cat >configure.ac <<EOF
# -*- Autoconf -*-

AC_PREREQ(2.61)
AC_INIT([$PROJ], [0.1], [$EMAIL])

AC_CONFIG_AUX_DIR(config)
AC_CONFIG_MACRO_DIR(m4)
AM_INIT_AUTOMAKE([1.11.1 foreign -Wall])
AC_CONFIG_SRCDIR([src/$PROJ.c])
AM_CONFIG_HEADER([config.h])
AC_CANONICAL_BUILD
AC_CANONICAL_HOST

AC_PROG_CC_C99
AC_C_INLINE
AC_C_FLEXIBLE_ARRAY_MEMBER
AM_PROG_CC_C_O
PKG_PROG_PKG_CONFIG([0.22])

EOF

for pname in $LIBS; do
    vname=$(echo $pname | tr a-z A-Z | tr - _)
    cat >>configure.ac <<EOF
PKG_CHECK_MODULES($vname, $pname)
AC_SUBST(${vname}_LIBS)
AC_SUBST(${vname}_CFLAGS)
AC_SUBST(${vname}_VERSION)

EOF
done

cat >>configure.ac <<EOF
AC_SUBST(libdir)
AC_SUBST(bindir)
AC_SUBST(includedir)
AC_CONFIG_FILES([Makefile])
AC_OUTPUT
EOF

######################################################################

echo "generating autogen.sh..."
cat >autogen.sh <<EOF
#!/bin/sh
set -x
rm -rf aclocal.m4 config.cache autom4te*.cache config.h.in
libtoolize --copy --force --automake || exit \$?
aclocal -I m4 --install --force || exit \$?
autoheader -f || exit \$?
automake --copy --gnu --add-missing || exit \$?
autoconf || exit \$?
EOF
chmod +x autogen.sh

######################################################################

echo "generating leak..."
cat >leak <<EOF
#!/bin/sh
exec valgrind --tool=memcheck --leak-check=yes --leak-resolution=high --show-reachable=yes --track-origins=yes --num-callers=20 --track-fds=yes \$@
EOF
chmod +x leak

######################################################################

echo "generating src/$PROJ.h..."
cat >src/$PROJ.h <<EOF
/*
 * $PROJ -- $DESCRIP
 * Copyright (c) $(date +%Y) $AUTHOR
 * Licensed $LICENSE
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include <errno.h>

EOF

for s in $LIBS; do
    if [[ -f /usr/include/$s.h || -f /usr/local/include/$s.h ]]; then
        echo "#include <$s.h>" >>src/$PROJ.h
        echo >>src/$PROJ.h
    fi
done

if echo $LIBS | grep sofia-sip-ua >/dev/null; then
    cat >>src/$PROJ.h <<EOF
#include <sofia-sip/su.h>
#include <sofia-sip/url.h>
#include <sofia-sip/bnf.h>
#include <sofia-sip/sdp.h>
#include <sofia-sip/msg.h>
#include <sofia-sip/nua.h>
#include <sofia-sip/su_log.h>
#include <sofia-sip/sdp_tag.h>
#include <sofia-sip/su_wait.h>
#include <sofia-sip/string0.h>
#include <sofia-sip/su_alloc.h>
#include <sofia-sip/msg_addr.h>
#include <sofia-sip/sip_util.h>
#include <sofia-sip/msg_types.h>
#include <sofia-sip/su_tag_io.h>
#include <sofia-sip/su_strlst.h>
#include <sofia-sip/su_vector.h>
#include <sofia-sip/sip_extra.h>
#include <sofia-sip/tport_tag.h>
#include <sofia-sip/sip_protos.h>
#include <sofia-sip/hostdomain.h>
#include <sofia-sip/sip_status.h>
#include <sofia-sip/sip_header.h>
#include <sofia-sip/sip_status.h>
#include <sofia-sip/http_status.h>
#include <sofia-sip/stun_common.h>
#include <sofia-sip/su_addrinfo.h>
#include <sofia-sip/su_uniqueid.h>
#include <sofia-sip/su_localinfo.h>

EOF
fi

cat >>src/$PROJ.h <<EOF
/* For Emacs:
 * Local Variables:
 * indent-tabs-mode:nil
 * tab-width:4
 * c-basic-offset:4
 * c-file-style:nil
 * End:
 * For VIM:
 * vim:set expandtab softtabstop=4 shiftwidth=4 tabstop=4:
 */
EOF

######################################################################

echo "generating src/$PROJ.c..."
cat >src/$PROJ.c <<EOF
/*
 * $PROJ -- $DESCRIP
 * Copyright (c) $(date +%Y) $AUTHOR
 * Licensed $LICENSE
 */

#include "$PROJ.h"

int main(int argc, char *argv[])
{
    printf("hello kitty\n");
    exit(0);
}

/* For Emacs:
 * Local Variables:
 * indent-tabs-mode:nil
 * tab-width:4
 * c-basic-offset:4
 * c-file-style:nil
 * End:
 * For VIM:
 * vim:set expandtab softtabstop=4 shiftwidth=4 tabstop=4:
 */
EOF

######################################################################

echo "generating src/test/test.c..."
cat >src/test/test.c <<EOF
#include "$PROJ.h"

int main(int argc, char *argv[])
{
    exit(0);
}
EOF

######################################################################

echo "generating .gdbinit..."
cat >.gdbinit <<EOF
# -*-GDB-Script-*-
#
# Tube .gdbinit
# Makes GDB fabulous
#
# This wouldn't be possible without all the code I stole from the
# wonderful .gdbinit maintained by the friendly hackers at
# reverse-engineering.net
#
# Some of the extra commands provided here (like 'reg') will only work
# on x86-64 machines.
#

set history save on
set history expansion on
set prompt \033[0;38;5;200m(>'.')> \033[0m
set confirm off
set verbose off
set print union on
set print array on
set print null-stop on
set print pretty on
set print sevenbit-strings on
set height 0
set width 0

# for those of us who aren't old men with beards
set disassembly-flavor intel


define flags
  # OF (overflow) flag
  if ((\$eflags >> 0xB) & 1)
    printf "O "
    set \$_of_flag = 1
  else
    printf "o "
    set \$_of_flag = 0
  end
  if ((\$eflags >> 0xA) & 1)
    printf "D "
  else
    printf "d "
  end
  if ((\$eflags >> 9) & 1)
    printf "I "
  else
    printf "i "
  end
  if ((\$eflags >> 8) & 1)
    printf "T "
  else
    printf "t "
  end
  # SF (sign) flag
  if ((\$eflags >> 7) & 1)
    printf "S "
    set \$_sf_flag = 1
  else
    printf "s "
    set \$_sf_flag = 0
  end
  # ZF (zero) flag
  if ((\$eflags >> 6) & 1)
    printf "Z "
    set \$_zf_flag = 1
  else
    printf "z "
    set \$_zf_flag = 0
  end
  if ((\$eflags >> 4) & 1)
    printf "A "
  else
    printf "a "
  end
  # PF (parity) flag
  if ((\$eflags >> 2) & 1)
    printf "P "
    set \$_pf_flag = 1
  else
    printf "p "
    set \$_pf_flag = 0
  end
  # CF (carry) flag
  if (\$eflags & 1)
    printf "C "
    set \$_cf_flag = 1
  else
    printf "c "
    set \$_cf_flag = 0
  end
  printf "\n"
end
document flags
Print flags register.
end


define eflags
  printf "     OF <%d>  DF <%d>  IF <%d>  TF <%d>",\
  ((\$eflags >> 0xB) & 1), ((\$eflags >> 0xA) & 1), \
  ((\$eflags >> 9) & 1), ((\$eflags >> 8) & 1)
  printf "  SF <%d>  ZF <%d>  AF <%d>  PF <%d>  CF <%d>\n",\
  ((\$eflags >> 7) & 1), ((\$eflags >> 6) & 1),\
  ((\$eflags >> 4) & 1), ((\$eflags >> 2) & 1), (\$eflags & 1)
  printf "     ID <%d>  VIP <%d> VIF <%d> AC <%d>",\
  ((\$eflags >> 0x15) & 1), ((\$eflags >> 0x14) & 1), \
  ((\$eflags >> 0x13) & 1), ((\$eflags >> 0x12) & 1)
  printf "  VM <%d>  RF <%d>  NT <%d>  IOPL <%d>\n",\
  ((\$eflags >> 0x11) & 1), ((\$eflags >> 0x10) & 1),\
  ((\$eflags >> 0xE) & 1), ((\$eflags >> 0xC) & 3)
end
document eflags
Print eflags register.
end


define reg
  echo \033[32m
  printf "RAX:"
  echo \033[0m
  printf "%016X  ", \$rax
  echo \033[32m
  printf "RBX:"
  echo \033[0m
  printf "%016X  ", \$rbx
  echo \033[32m
  printf "RCX:"
  echo \033[0m
  printf "%016X  ", \$rcx
  echo \033[32m
  printf "RDX:"
  echo \033[0m
  printf "%016X\n", \$rdx

  echo \033[32m
  printf " R8:"
  echo \033[0m
  printf "%016X  ", \$r8
  echo \033[32m
  printf " R9:"
  echo \033[0m
  printf "%016X  ", \$r9
  echo \033[32m
  printf "R10:"
  echo \033[0m
  printf "%016X  ", \$r10
  echo \033[32m
  printf "R11:"
  echo \033[0m
  printf "%016X\n", \$r11
  echo \033[32m

  printf "R12:"
  echo \033[0m
  printf "%016X  ", \$r12
  echo \033[32m
  printf "R13:"
  echo \033[0m
  printf "%016X  ", \$r13
  echo \033[32m
  printf "R14:"
  echo \033[0m
  printf "%016X  ", \$r14
  echo \033[32m
  printf "R15:"
  echo \033[0m
  printf "%016X\n", \$r15

  echo \033[32m
  printf "RSI:"
  echo \033[0m
  printf "%016X  ", \$rsi
  echo \033[32m
  printf "RDI:"
  echo \033[0m
  printf "%016X  ", \$rdi
  echo \033[32m
  printf "RBP:"
  echo \033[0m
  printf "%016X  ", \$rbp
  echo \033[32m
  printf "RSP:"
  echo \033[0m
  printf "%016X\n", \$rsp

  echo \033[32m
  printf "RIP:"
  echo \033[0m
  printf "%016X", \$rip

  printf "  "
  echo \033[1;31m
  flags
  echo \033[0m

  # # call smallregisters
  # smallregisters

  # # display conditional jump routine
  # dumpjump
  # printf "\n"
end
document reg
Print CPU registers.  Currently x86-64 only.
end


define init
  tbreak _init
  r
end
document init
Run program and break on _init().
end


define start
  tbreak _start
  r
end
document start
Run program and break on _start().
end


define sstart
  tbreak __libc_start_main
  r
end
document sstart
Run program and break on __libc_start_main().
Useful for stripped executables.
end


define main
  tbreak main
  r
end
document main
Run program and break on main().
end
EOF

######################################################################

git init
git add .
git commit -m "c-bone initial import" \
           --author="Justine Tunney <jtunney@lobstertech.com>"

cat <<EOF

----------------------------------------------------------------------
                              All Done!

To get started you should run:

    cd $PROJ
    ./autogen.sh
    ./configure -C CFLAGS="-g3 -O0 -Wall -pedantic"
    make -j2
    ./$PROJ

EOF
